import 'package:flutter/material.dart';

ThemeData THEMEDATA = ThemeData(
  canvasColor: const Color(0xfffdfcff),
  cardColor: const Color(0xfffdfcff),
  colorScheme: const ColorScheme(
    background: Color(0xfffdfcff),
    brightness: Brightness.light,
    error: Color(0xffba1a1a),
    errorContainer: Color(0xffffdad6),
    inversePrimary: Color(0xff9ecaff),
    inverseSurface: Color(0xff2f3033),
    onBackground: Color(0xff1a1c1e),
    onError: Color(0xffffffff),
    onErrorContainer: Color(0xff410002),
    onInverseSurface: Color(0xfff1f0f4),
    onPrimary: Color(0xffffffff),
    onPrimaryContainer: Color(0xff001d36),
    onSecondary: Color(0xffffffff),
    onSecondaryContainer: Color(0xff101c2b),
    onSurface: Color(0xff1a1c1e),
    onSurfaceVariant: Color(0xff43474e),
    onTertiary: Color(0xffffffff),
    onTertiaryContainer: Color(0xff251431),
    outline: Color(0xff73777f),
    outlineVariant: Color(0xffc3c7cf),
    primary: Color(0xff0061a4),
    primaryContainer: Color(0xffd1e4ff),
    scrim: Color(0xff000000),
    secondary: Color(0xff535f70),
    secondaryContainer: Color(0xffd7e3f7),
    shadow: Color(0xff000000),
    surface: Color(0xfffdfcff),
    surfaceTint: Color(0xff0061a4),
    surfaceVariant: Color(0xffdfe2eb),
    tertiary: Color(0xff6b5778),
    tertiaryContainer: Color(0xfff2daff),
  ),
  dialogBackgroundColor: const Color(0xfffdfcff),
  disabledColor: const Color(0x61000000),
  dividerColor: const Color(0x1f1a1c1e),
  focusColor: const Color(0x1f000000),
  highlightColor: const Color(0x66bcbcbc),
  hintColor: const Color(0x99000000),
  hoverColor: const Color(0x0a000000),
  indicatorColor: const Color(0xffffffff),
  buttonTheme: ButtonThemeData(
    colorScheme: ColorScheme.fromSwatch(),
    alignedDropdown: false,
  ),
  fontFamily: 'Segoe UI',
  primaryTextTheme: const TextTheme(
    bodyLarge: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodyMedium: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodySmall: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 12,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.4,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayLarge: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 96,
      fontWeight: FontWeight.w300,
      inherit: false,
      letterSpacing: -1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayMedium: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 60,
      fontWeight: FontWeight.w300,
      inherit: false,
      letterSpacing: -0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displaySmall: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 48,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineLarge: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 40,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineMedium: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 34,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineSmall: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 24,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelLarge: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 1.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelMedium: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 11,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelSmall: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 10,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleLarge: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 20,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleMedium: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleSmall: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w500,
      inherit: false,
      letterSpacing: 0.1,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  scaffoldBackgroundColor: const Color.fromARGB(214, 252, 253, 255),
  secondaryHeaderColor: const Color(0xffe3f2fd),
  shadowColor: const Color(0xff000000),
  splashColor: const Color(0x66c8c8c8),
  textTheme: const TextTheme(
    bodyLarge: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodyMedium: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    bodySmall: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 12,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.4,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayLarge: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 96,
      fontWeight: FontWeight.w300,
      inherit: false,
      // letterSpacing: -1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displayMedium: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 60,
      fontWeight: FontWeight.w300,
      inherit: false,
      // letterSpacing: -0.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    displaySmall: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 48,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineLarge: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 40,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineMedium: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 34,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    headlineSmall: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 24,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelLarge: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w500,
      inherit: false,
      // letterSpacing: 1.25,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelMedium: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 11,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    labelSmall: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 10,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 1.5,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleLarge: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 20,
      fontWeight: FontWeight.w500,
      inherit: false,
      // letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleMedium: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.15,
      textBaseline: TextBaseline.alphabetic,
    ),
    titleSmall: TextStyle(
      color: Color(0xff1a1c1e),
      decoration: TextDecoration.none,
      decorationColor: Color(0xff1a1c1e),
      fontFamily: 'Segoe UI',
      fontSize: 14,
      fontWeight: FontWeight.w400,
      inherit: false,
      // letterSpacing: 0.1,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
  appBarTheme: const AppBarTheme(
    color: Color(0xff001d36),
    foregroundColor: Color(0xfffdfcff),
    titleTextStyle: TextStyle(
      color: Color(0xfffdfcff),
      decoration: TextDecoration.none,
      decorationColor: Color(0xfffdfcff),
      fontFamily: 'Anton',
      fontSize: 20,
      fontWeight: FontWeight.w500,
      inherit: false,
      textBaseline: TextBaseline.alphabetic,
    ),
  ),
);
